version: "3.9"
services:
  app:
    build:
      dockerfile: deployments/Dockerfile
      context: ..
    restart: on-failure
    depends_on:
      - rabbitmq
    ports:
      - "8080:8080"
    networks:
      - container-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=myuser
      - RABBITMQ_DEFAULT_PASS=mypassword
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - container-network

networks:
  container-network:
    driver: bridge